[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<4.0"
dependencies = [
    "aiogram>=3.20.0.post0",
    "supabase>=2.15.3",
    "python-dotenv"
    ]
